CREATE TABLE flow_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    CONSTRAINT fk_flow_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_flow_user_id ON flow_tokens(user_id);
CREATE INDEX idx_flow_type ON flow_tokens(type);
